### ISSUE TITLE
[BUG]: "c is not defined" error in Stores nested reactivity playground tutorial

### ISSUE THREAD

**Issue by jenishngl** [solidjs/solid-playground#151]
In the Playground [Stores nested reactivity](https://www.solidjs.com/tutorial/stores_nested_reactivity?solved) even after clicking on solve throws an error as 

```
c is not defined
at Object.fn (blob:https://www.solidjs.com/3b9da96b-4f17-4a73-9277-a86c079f1baa:8:24)
at runComputation (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:688:22)
at updateComputation (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:671:3)
at runTop (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:788:7)
at runQueue (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:875:5)
at completeUpdates (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:824:7)
at runUpdates (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:810:5)
at writeSignal (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:635:7)
at setter (https://cdn.skypack.dev/-/solid-js@v1.7.11-8423VVsYWPLIcUbulGlF/dist=es2019,mode=imports/optimized/common/solid-647953fd.js:185:12)
at addTodo (blob:https://www.solidjs.com/525c0f59-0c04-40b0-81b7-8c3da87e1bc7:14:5)
```

Attaching a screenshot from Chrome 115.0.5790.171 on Windows 11

<img width="1697" alt="image" src="https://github.com/solidjs/solid-playground/assets/9320926/5f5a643e-7b0e-4a53-b30c-f6dbd03e3ac4">

**Comment by modderme123** [comment]
I'm having trouble reproducing this... Maybe try a hard refresh?

**Comment by jenishngl** [comment]
> I'm having trouble reproducing this... Maybe try a hard refresh?

yep. After refreshing cache its working fine
